name: Run Lighthouse CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.9.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.x
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.14.x
          npm run lighthouse
        env:
          LIGHTHOUSE_COLLECT_URL: "https://stage.firefoxmonitor.nonprod.cloudops.mozgcp.net"
